// Default array of languages for when the API is unreachable
// Generated using: var array = await getWikis(); console.log(JSON.stringify(array))
const defaultWikiArray = [
    ["aa", "Qafár af"],
    ["ab", "Аҧсшәа"],
    ["ace", "Acèh"],
    ["ady", "адыгабзэ"],
    ["af", "Afrikaans"],
    ["ak", "Akan"],
    ["als", "Alemannisch"],
    ["am", "አማርኛ"],
    ["an", "aragonés"],
    ["ang", "Ænglisc"],
    ["ar", "العربية"],
    ["arc", "ܐܪܡܝܐ"],
    ["arz", "مصرى"],
    ["as", "অসমীয়া"],
    ["ast", "asturianu"],
    ["atj", "Atikamekw"],
    ["av", "авар"],
    ["ay", "Aymar aru"],
    ["az", "azərbaycanca"],
    ["azb", "تۆرکجه"],
    ["ba", "башҡортса"],
    ["ban", "Bali"],
    ["bar", "Boarisch"],
    ["bat-smg", "žemaitėška"],
    ["bcl", "Bikol Central"],
    ["be", "беларуская"],
    ["be-x-old", "беларуская (тарашкевіца)‎"],
    ["bg", "български"],
    ["bh", "भोजपुरी"],
    ["bi", "Bislama"],
    ["bjn", "Banjar"],
    ["bm", "bamanankan"],
    ["bn", "বাংলা"],
    ["bo", "བོད་ཡིག"],
    ["bpy", "বিষ্ণুপ্রিয়া মণিপুরী"],
    ["br", "brezhoneg"],
    ["bs", "bosanski"],
    ["bug", "ᨅᨔ ᨕᨘᨁᨗ"],
    ["bxr", "буряад"],
    ["ca", "català"],
    ["cbk-zam", "Chavacano de Zamboanga"],
    ["cdo", "Mìng-dĕ̤ng-ngṳ̄"],
    ["ce", "нохчийн"],
    ["ceb", "Cebuano"],
    ["ch", "Chamoru"],
    ["cho", "Choctaw"],
    ["chr", "ᏣᎳᎩ"],
    ["chy", "Tsetsêhestâhese"],
    ["ckb", "کوردی"],
    ["co", "corsu"],
    ["cr", "Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ"],
    ["crh", "qırımtatarca"],
    ["cs", "čeština"],
    ["csb", "kaszëbsczi"],
    ["cu", "словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ"],
    ["cv", "Чӑвашла"],
    ["cy", "Cymraeg"],
    ["da", "dansk"],
    ["de", "Deutsch"],
    ["din", "Thuɔŋjäŋ"],
    ["diq", "Zazaki"],
    ["dsb", "dolnoserbski"],
    ["dty", "डोटेली"],
    ["dv", "ދިވެހިބަސް"],
    ["dz", "ཇོང་ཁ"],
    ["ee", "eʋegbe"],
    ["el", "Ελληνικά"],
    ["eml", "emiliàn e rumagnòl"],
    ["en", "English"],
    ["eo", "Esperanto"],
    ["es", "español"],
    ["et", "eesti"],
    ["eu", "euskara"],
    ["ext", "estremeñu"],
    ["fa", "فارسی"],
    ["ff", "Fulfulde"],
    ["fi", "suomi"],
    ["fiu-vro", "Võro"],
    ["fj", "Na Vosa Vakaviti"],
    ["fo", "føroyskt"],
    ["fr", "français"],
    ["frp", "arpetan"],
    ["frr", "Nordfriisk"],
    ["fur", "furlan"],
    ["fy", "Frysk"],
    ["ga", "Gaeilge"],
    ["gag", "Gagauz"],
    ["gan", "贛語"],
    ["gcr", "kriyòl gwiyannen"],
    ["gd", "Gàidhlig"],
    ["gl", "galego"],
    ["glk", "گیلکی"],
    ["gn", "Avañe'ẽ"],
    ["gom", "गोंयची कोंकणी / Gõychi Konknni"],
    ["gor", "Bahasa Hulontalo"],
    ["got", "𐌲𐌿𐍄𐌹𐍃𐌺"],
    ["gu", "ગુજરાતી"],
    ["gv", "Gaelg"],
    ["ha", "Hausa"],
    ["hak", "客家語/Hak-kâ-ngî"],
    ["haw", "Hawaiʻi"],
    ["he", "עברית"],
    ["hi", "हिन्दी"],
    ["hif", "Fiji Hindi"],
    ["ho", "Hiri Motu"],
    ["hr", "hrvatski"],
    ["hsb", "hornjoserbsce"],
    ["ht", "Kreyòl ayisyen"],
    ["hu", "magyar"],
    ["hy", "հայերեն"],
    ["hyw", "Արեւմտահայերէն"],
    ["hz", "Otsiherero"],
    ["ia", "interlingua"],
    ["id", "Bahasa Indonesia"],
    ["ie", "Interlingue"],
    ["ig", "Igbo"],
    ["ii", "ꆇꉙ"],
    ["ik", "Iñupiak"],
    ["ilo", "Ilokano"],
    ["inh", "ГӀалгӀай"],
    ["io", "Ido"],
    ["is", "íslenska"],
    ["it", "italiano"],
    ["iu", "ᐃᓄᒃᑎᑐᑦ/inuktitut"],
    ["ja", "日本語"],
    ["jam", "Patois"],
    ["jbo", "la .lojban."],
    ["jv", "Jawa"],
    ["ka", "ქართული"],
    ["kaa", "Qaraqalpaqsha"],
    ["kab", "Taqbaylit"],
    ["kbd", "Адыгэбзэ"],
    ["kbp", "Kabɩyɛ"],
    ["kg", "Kongo"],
    ["ki", "Gĩkũyũ"],
    ["kj", "Kwanyama"],
    ["kk", "қазақша"],
    ["kl", "kalaallisut"],
    ["km", "ភាសាខ្មែរ"],
    ["kn", "ಕನ್ನಡ"],
    ["ko", "한국어"],
    ["koi", "Перем Коми"],
    ["kr", "Kanuri"],
    ["krc", "къарачай-малкъар"],
    ["ks", "कॉशुर / کٲشُر"],
    ["ksh", "Ripoarisch"],
    ["ku", "kurdî"],
    ["kv", "коми"],
    ["kw", "kernowek"],
    ["ky", "Кыргызча"],
    ["la", "Latina"],
    ["lad", "Ladino"],
    ["lb", "Lëtzebuergesch"],
    ["lbe", "лакку"],
    ["lez", "лезги"],
    ["lfn", "Lingua Franca Nova"],
    ["lg", "Luganda"],
    ["li", "Limburgs"],
    ["lij", "Ligure"],
    ["lmo", "lumbaart"],
    ["ln", "lingála"],
    ["lo", "ລາວ"],
    ["lrc", "لۊری شومالی"],
    ["lt", "lietuvių"],
    ["ltg", "latgaļu"],
    ["lv", "latviešu"],
    ["mai", "मैथिली"],
    ["map-bms", "Basa Banyumasan"],
    ["mdf", "мокшень"],
    ["mg", "Malagasy"],
    ["mh", "Ebon"],
    ["mhr", "олык марий"],
    ["mi", "Māori"],
    ["min", "Minangkabau"],
    ["mk", "македонски"],
    ["ml", "മലയാളം"],
    ["mn", "монгол"],
    ["mnw", "ဘာသာ မန်"],
    ["mo", "молдовеняскэ"],
    ["mr", "मराठी"],
    ["mrj", "кырык мары"],
    ["ms", "Bahasa Melayu"],
    ["mt", "Malti"],
    ["mus", "Mvskoke"],
    ["mwl", "Mirandés"],
    ["my", "မြန်မာဘာသာ"],
    ["myv", "эрзянь"],
    ["mzn", "مازِرونی"],
    ["na", "Dorerin Naoero"],
    ["nah", "Nāhuatl"],
    ["nap", "Napulitano"],
    ["nds", "Plattdüütsch"],
    ["nds-nl", "Nedersaksies"],
    ["ne", "नेपाली"],
    ["new", "नेपाल भाषा"],
    ["ng", "Oshiwambo"],
    ["nl", "Nederlands"],
    ["nn", "norsk nynorsk"],
    ["no", "norsk"],
    ["nov", "Novial"],
    ["nqo", "ߒߞߏ"],
    ["nrm", "Nouormand"],
    ["nso", "Sesotho sa Leboa"],
    ["nv", "Diné bizaad"],
    ["ny", "Chi-Chewa"],
    ["oc", "occitan"],
    ["olo", "Livvinkarjala"],
    ["om", "Oromoo"],
    ["or", "ଓଡ଼ିଆ"],
    ["os", "Ирон"],
    ["pa", "ਪੰਜਾਬੀ"],
    ["pag", "Pangasinan"],
    ["pam", "Kapampangan"],
    ["pap", "Papiamentu"],
    ["pcd", "Picard"],
    ["pdc", "Deitsch"],
    ["pfl", "Pälzisch"],
    ["pi", "पालि"],
    ["pih", "Norfuk / Pitkern"],
    ["pl", "polski"],
    ["pms", "Piemontèis"],
    ["pnb", "پنجابی"],
    ["pnt", "Ποντιακά"],
    ["ps", "پښتو"],
    ["pt", "português"],
    ["qu", "Runa Simi"],
    ["rm", "rumantsch"],
    ["rmy", "romani čhib"],
    ["rn", "Kirundi"],
    ["ro", "română"],
    ["roa-rup", "armãneashti"],
    ["roa-tara", "tarandíne"],
    ["ru", "русский"],
    ["rue", "русиньскый"],
    ["rw", "Kinyarwanda"],
    ["sa", "संस्कृतम्"],
    ["sah", "саха тыла"],
    ["sat", "ᱥᱟᱱᱛᱟᱲᱤ"],
    ["sc", "sardu"],
    ["scn", "sicilianu"],
    ["sco", "Scots"],
    ["sd", "سنڌي"],
    ["se", "davvisámegiella"],
    ["sg", "Sängö"],
    ["sh", "srpskohrvatski / српскохрватски"],
    ["shn", "ၽႃႇသႃႇတႆး "],
    ["si", "සිංහල"],
    ["simple", "Simple English"],
    ["sk", "slovenčina"],
    ["sl", "slovenščina"],
    ["sm", "Gagana Samoa"],
    ["sn", "chiShona"],
    ["so", "Soomaaliga"],
    ["sq", "shqip"],
    ["sr", "српски / srpski"],
    ["srn", "Sranantongo"],
    ["ss", "SiSwati"],
    ["st", "Sesotho"],
    ["stq", "Seeltersk"],
    ["su", "Sunda"],
    ["sv", "svenska"],
    ["sw", "Kiswahili"],
    ["szl", "ślůnski"],
    ["szy", "Sakizaya"],
    ["ta", "தமிழ்"],
    ["tcy", "ತುಳು"],
    ["te", "తెలుగు"],
    ["tet", "tetun"],
    ["tg", "тоҷикӣ"],
    ["th", "ไทย"],
    ["ti", "ትግርኛ"],
    ["tk", "Türkmençe"],
    ["tl", "Tagalog"],
    ["tn", "Setswana"],
    ["to", "lea faka-Tonga"],
    ["tpi", "Tok Pisin"],
    ["tr", "Türkçe"],
    ["ts", "Xitsonga"],
    ["tt", "татарча/tatarça"],
    ["tum", "chiTumbuka"],
    ["tw", "Twi"],
    ["ty", "reo tahiti"],
    ["tyv", "тыва дыл"],
    ["udm", "удмурт"],
    ["ug", "ئۇيغۇرچە / Uyghurche"],
    ["uk", "українська"],
    ["ur", "اردو"],
    ["uz", "oʻzbekcha/ўзбекча"],
    ["ve", "Tshivenda"],
    ["vec", "vèneto"],
    ["vep", "vepsän kel’"],
    ["vi", "Tiếng Việt"],
    ["vls", "West-Vlams"],
    ["vo", "Volapük"],
    ["wa", "walon"],
    ["war", "Winaray"],
    ["wo", "Wolof"],
    ["wuu", "吴语"],
    ["xal", "хальмг"],
    ["xh", "isiXhosa"],
    ["xmf", "მარგალური"],
    ["yi", "ייִדיש"],
    ["yo", "Yorùbá"],
    ["yue", "粵語"],
    ["za", "Vahcuengh"],
    ["zea", "Zeêuws"],
    ["zh", "中文"],
    ["zh-classical", "文言"],
    ["zh-min-nan", "Bân-lâm-gú"],
    ["zh-yue", "粵語"],
    ["zu", "isiZulu"],
    ["nb", "norsk bokmål"],
    ["zh-cn", "中文（中国大陆）‎"],
    ["zh-tw", "中文（台灣）‎"],
    ["nan", "Bân-lâm-gú"],
    ["vro", "Võro"],
    ["lzh", "文言"],
    ["rup", "armãneashti"],
    ["gsw", "Alemannisch"],
    ["be-tarask", "беларуская (тарашкевіца)‎"],
    ["sgs", "žemaitėška"],
    ["egl", "Emiliàn"]
]

// Function for obtaining updated list of Wikipedias
async function getWikis() {
    // Download list of Wikis
    try {
        const response = await fetch('https://sv.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=interwikimap&sifilteriw=local&format=json', {
            headers: {
                'Content-Type': 'application/json'
            }
        })
        if (!response.ok) {
            console.log('Could not obtain data from Wikipedia API.')
            return defaultWikiArray
        }
        const json = await response.json()
        // Parse list
        const wikiList = json.query.interwikimap
        console.log('Wiki list downloaded, contains ' + wikiList.length + ' items.')
        // Create new array with only the active language wikis
        var wikiArray = []
        for (i in wikiList) {
            if (wikiList[i].language) {
                wikiArray.push([wikiList[i].prefix, wikiList[i].language])
            }
        }
        return wikiArray
    } catch (error) {
        console.log('Could not obtain data from Wikipedia API: ' + error)
        return defaultWikiArray
    }
}