// Default list of Wikipedia languages
// Run in extension's console to get updated list: updateWikis().then(function(data){console.log(data)});
const defaultWikiList = {
    "ab": "аԥсшәа",
    "ace": "Acèh",
    "ady": "адыгабзэ",
    "af": "Afrikaans",
    "alt": "алтай тил",
    "am": "አማርኛ",
    "ami": "Pangcah",
    "an": "aragonés",
    "ang": "Ænglisc",
    "ann": "Obolo",
    "anp": "अंगिका",
    "ar": "العربية",
    "arc": "ܐܪܡܝܐ",
    "ary": "الدارجة",
    "arz": "مصرى",
    "as": "অসমীয়া",
    "ast": "asturianu",
    "atj": "Atikamekw",
    "av": "авар",
    "avk": "Kotava",
    "awa": "अवधी",
    "ay": "Aymar aru",
    "az": "azərbaycanca",
    "azb": "تۆرکجه",
    "ba": "башҡортса",
    "ban": "Basa Bali",
    "bar": "Boarisch",
    "bbc": "Batak Toba",
    "bcl": "Bikol Central",
    "bdr": "Bajau Sama",
    "be": "беларуская",
    "be-tarask": "беларуская (тарашкевіца)",
    "bew": "Betawi",
    "bg": "български",
    "bh": "भोजपुरी",
    "bi": "Bislama",
    "bjn": "Banjar",
    "blk": "ပအိုဝ်ႏဘာႏသာႏ",
    "bm": "bamanankan",
    "bn": "বাংলা",
    "bo": "བོད་ཡིག",
    "bpy": "বিষ্ণুপ্রিয়া মণিপুরী",
    "br": "brezhoneg",
    "bs": "bosanski",
    "btm": "Batak Mandailing",
    "bug": "Basa Ugi",
    "bxr": "буряад",
    "ca": "català",
    "cbk-zam": "Chavacano de Zamboanga",
    "cdo": "閩東語 / Mìng-dĕ̤ng-ngṳ̄",
    "ce": "нохчийн",
    "ceb": "Cebuano",
    "ch": "Chamoru",
    "chr": "ᏣᎳᎩ",
    "chy": "Tsetsêhestâhese",
    "ckb": "کوردی",
    "co": "corsu",
    "crh": "qırımtatarca",
    "cs": "čeština",
    "csb": "kaszëbsczi",
    "cu": "словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ",
    "cv": "чӑвашла",
    "cy": "Cymraeg",
    "da": "dansk",
    "dag": "dagbanli",
    "de": "Deutsch",
    "dga": "Dagaare",
    "din": "Thuɔŋjäŋ",
    "diq": "Zazaki",
    "dsb": "dolnoserbski",
    "dtp": "Kadazandusun",
    "dty": "डोटेली",
    "dv": "ދިވެހިބަސް",
    "dz": "ཇོང་ཁ",
    "ee": "eʋegbe",
    "el": "Ελληνικά",
    "eml": "emiliàn e rumagnòl",
    "en": "English",
    "eo": "Esperanto",
    "es": "español",
    "et": "eesti",
    "eu": "euskara",
    "ext": "estremeñu",
    "fa": "فارسی",
    "fat": "mfantse",
    "ff": "Fulfulde",
    "fi": "suomi",
    "fj": "Na Vosa Vakaviti",
    "fo": "føroyskt",
    "fon": "fɔ̀ngbè",
    "fr": "français",
    "frp": "arpetan",
    "frr": "Nordfriisk",
    "fur": "furlan",
    "fy": "Frysk",
    "ga": "Gaeilge",
    "gag": "Gagauz",
    "gan": "贛語",
    "gcr": "kriyòl gwiyannen",
    "gd": "Gàidhlig",
    "gl": "galego",
    "glk": "گیلکی",
    "gn": "Avañe'ẽ",
    "gom": "गोंयची कोंकणी / Gõychi Konknni",
    "gor": "Bahasa Hulontalo",
    "got": "𐌲𐌿𐍄𐌹𐍃𐌺",
    "gpe": "Ghanaian Pidgin",
    "gsw": "Alemannisch",
    "gu": "ગુજરાતી",
    "guc": "wayuunaiki",
    "gur": "farefare",
    "guw": "gungbe",
    "gv": "Gaelg",
    "ha": "Hausa",
    "hak": "客家語 / Hak-kâ-ngî",
    "haw": "Hawaiʻi",
    "he": "עברית",
    "hi": "हिन्दी",
    "hif": "Fiji Hindi",
    "hr": "hrvatski",
    "hsb": "hornjoserbsce",
    "ht": "Kreyòl ayisyen",
    "hu": "magyar",
    "hy": "հայերեն",
    "hyw": "Արեւմտահայերէն",
    "ia": "interlingua",
    "iba": "Jaku Iban",
    "id": "Bahasa Indonesia",
    "ie": "Interlingue",
    "ig": "Igbo",
    "igl": "Igala",
    "ik": "Iñupiatun",
    "ilo": "Ilokano",
    "inh": "гӀалгӀай",
    "io": "Ido",
    "is": "íslenska",
    "it": "italiano",
    "iu": "ᐃᓄᒃᑎᑐᑦ / inuktitut",
    "ja": "日本語",
    "jam": "Patois",
    "jbo": "la .lojban.",
    "jv": "Jawa",
    "ka": "ქართული",
    "kaa": "Qaraqalpaqsha",
    "kab": "Taqbaylit",
    "kbd": "адыгэбзэ",
    "kbp": "Kabɩyɛ",
    "kcg": "Tyap",
    "kg": "Kongo",
    "kge": "Kumoring",
    "ki": "Gĩkũyũ",
    "kk": "қазақша",
    "km": "ភាសាខ្មែរ",
    "kn": "ಕನ್ನಡ",
    "knc": "Yerwa Kanuri",
    "ko": "한국어",
    "koi": "перем коми",
    "krc": "къарачай-малкъар",
    "ks": "کٲشُر",
    "ksh": "Ripoarisch",
    "ku": "kurdî",
    "kus": "Kʋsaal",
    "kv": "коми",
    "kw": "kernowek",
    "ky": "кыргызча",
    "la": "Latina",
    "lad": "Ladino",
    "lb": "Lëtzebuergesch",
    "lbe": "лакку",
    "lez": "лезги",
    "lfn": "Lingua Franca Nova",
    "lg": "Luganda",
    "li": "Limburgs",
    "lij": "Ligure",
    "lld": "Ladin",
    "lmo": "lombard",
    "ln": "lingála",
    "lo": "ລາວ",
    "lt": "lietuvių",
    "ltg": "latgaļu",
    "lv": "latviešu",
    "lzh": "文言",
    "mad": "Madhurâ",
    "mai": "मैथिली",
    "map-bms": "Basa Banyumasan",
    "mdf": "мокшень",
    "mg": "Malagasy",
    "mhr": "олык марий",
    "mi": "Māori",
    "min": "Minangkabau",
    "mk": "македонски",
    "ml": "മലയാളം",
    "mn": "монгол",
    "mni": "ꯃꯤꯇꯩ ꯂꯣꯟ",
    "mnw": "ဘာသာမန်",
    "mos": "moore",
    "mr": "मराठी",
    "mrj": "кырык мары",
    "ms": "Bahasa Melayu",
    "mt": "Malti",
    "mwl": "Mirandés",
    "my": "မြန်မာဘာသာ",
    "myv": "эрзянь",
    "mzn": "مازِرونی",
    "nah": "Nāhuatl",
    "nan": "閩南語 / Bân-lâm-gí",
    "nap": "Napulitano",
    "nds": "Plattdüütsch",
    "nds-nl": "Nedersaksies",
    "ne": "नेपाली",
    "new": "नेपाल भाषा",
    "nia": "Li Niha",
    "nl": "Nederlands",
    "nn": "norsk nynorsk",
    "no": "norsk",
    "nov": "Novial",
    "nqo": "ߒߞߏ",
    "nr": "isiNdebele seSewula",
    "nrm": "Nouormand",
    "nso": "Sesotho sa Leboa",
    "nup": "Nupe",
    "nv": "Diné bizaad",
    "ny": "Chi-Chewa",
    "oc": "occitan",
    "olo": "livvinkarjala",
    "om": "Oromoo",
    "or": "ଓଡ଼ିଆ",
    "os": "ирон",
    "pa": "ਪੰਜਾਬੀ",
    "pag": "Pangasinan",
    "pam": "Kapampangan",
    "pap": "Papiamentu",
    "pcd": "Picard",
    "pcm": "Naijá",
    "pdc": "Deitsch",
    "pfl": "Pälzisch",
    "pi": "पालि",
    "pl": "polski",
    "pms": "Piemontèis",
    "pnb": "پنجابی",
    "pnt": "Ποντιακά",
    "ps": "پښتو",
    "pt": "português",
    "pwn": "pinayuanan",
    "qu": "Runa Simi",
    "rki": "ရခိုင်",
    "rm": "rumantsch",
    "rmy": "romani čhib",
    "rn": "ikirundi",
    "ro": "română",
    "roa-tara": "tarandíne",
    "rsk": "руски",
    "ru": "русский",
    "rue": "русиньскый",
    "rup": "armãneashti",
    "rw": "Ikinyarwanda",
    "sa": "संस्कृतम्",
    "sah": "саха тыла",
    "sat": "ᱥᱟᱱᱛᱟᱲᱤ",
    "sc": "sardu",
    "scn": "sicilianu",
    "sco": "Scots",
    "sd": "سنڌي",
    "se": "davvisámegiella",
    "sg": "Sängö",
    "sgs": "žemaitėška",
    "sh": "srpskohrvatski / српскохрватски",
    "shi": "Taclḥit",
    "shn": "တႆး",
    "shy": "tacawit",
    "si": "සිංහල",
    "simple": "Simple English",
    "sk": "slovenčina",
    "skr": "سرائیکی",
    "sl": "slovenščina",
    "sm": "Gagana Samoa",
    "smn": "anarâškielâ",
    "sn": "chiShona",
    "so": "Soomaaliga",
    "sq": "shqip",
    "sr": "српски / srpski",
    "srn": "Sranantongo",
    "ss": "SiSwati",
    "st": "Sesotho",
    "stq": "Seeltersk",
    "su": "Sunda",
    "sv": "svenska",
    "sw": "Kiswahili",
    "syl": "ꠍꠤꠟꠐꠤ",
    "szl": "ślůnski",
    "szy": "Sakizaya",
    "ta": "தமிழ்",
    "tay": "Tayal",
    "tcy": "ತುಳು",
    "tdd": "ᥖᥭᥰ ᥖᥬᥲ ᥑᥨᥒᥰ",
    "te": "తెలుగు",
    "tet": "tetun",
    "tg": "тоҷикӣ",
    "th": "ไทย",
    "ti": "ትግርኛ",
    "tig": "ትግሬ",
    "tk": "Türkmençe",
    "tl": "Tagalog",
    "tly": "tolışi",
    "tn": "Setswana",
    "to": "lea faka-Tonga",
    "tok": "toki pona",
    "tpi": "Tok Pisin",
    "tr": "Türkçe",
    "trv": "Seediq",
    "ts": "Xitsonga",
    "tt": "татарча / tatarça",
    "tum": "chiTumbuka",
    "tw": "Twi",
    "ty": "reo tahiti",
    "tyv": "тыва дыл",
    "udm": "удмурт",
    "ug": "ئۇيغۇرچە / Uyghurche",
    "uk": "українська",
    "ur": "اردو",
    "uz": "oʻzbekcha / ўзбекча",
    "ve": "Tshivenda",
    "vec": "vèneto",
    "vep": "vepsän kel’",
    "vi": "Tiếng Việt",
    "vls": "West-Vlams",
    "vo": "Volapük",
    "vro": "võro",
    "wa": "walon",
    "war": "Winaray",
    "wo": "Wolof",
    "wuu": "吴语",
    "xal": "хальмг",
    "xh": "isiXhosa",
    "xmf": "მარგალური",
    "yi": "ייִדיש",
    "yo": "Yorùbá",
    "yue": "粵語",
    "za": "Vahcuengh",
    "zea": "Zeêuws",
    "zgh": "ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ",
    "zh": "中文",
    "zu": "isiZulu"
}

/**
 * Function to obtain list of active Wikipedia sites using official Wikimedia API.
 * 
 * More information: https://www.mediawiki.org/wiki/Extension:SiteMatrix
 * @returns {Promise} Promise that resolves with a JSON object, or rejects with an error
 */
function updateWikis() {
    return new Promise(async function (resolve, reject) {
        const response = await fetch('https://en.wikipedia.org/w/api.php?action=sitematrix&format=json&smtype=language');
        if (!response.ok) {
            reject();
        }
        const json = await response.json();
        // Create list of active Wikipedia sites as object
        let wikisObj = {};
        for (item in json.sitematrix) {
            // Check if the language has an associated Wikipedia website
            if (Object.hasOwn(json.sitematrix[item], 'site') && json.sitematrix[item].site.length) {
                // Check that the language's Wikipedia isn't closed
                if (!Object.hasOwn(json.sitematrix[item].site[0], 'closed')) {
                    wikisObj[json.sitematrix[item].code] = json.sitematrix[item].name;
                } else {
                    continue;
                }
            }
        }
        // Resolve the promise with the new list
        resolve(wikisObj);
    })
}

/**
 * Function to get the list of Wikipedia sites. If no user-updated list is available, the default list is returned.
 * @returns {Promise} Promise that resolves with a JSON object
 */
async function getWikis() {
    return new Promise(async function (resolve, reject) {
        // Check for updated list of Wikipedia sites
        const data = await chrome.storage.sync.get(['wikiList']);
        if (data.wikiList) {
            resolve(data.wikiList);
        } else {
            // No updated list has been stored, send the default list
            resolve(defaultWikiList);
        }
    })
}

// Function for detecting system language and setting it to the default search language
async function resetToSystemLanguage() {
    var lang = navigator.languages[0]
    var newLang = ''
    // Cut off the localization part if it exists (e.g. en-US becomes en), to match with Wikipedia's format
    var n = lang.indexOf('-')
    lang = lang.substring(0, n != -1 ? n : lang.length)
    // Check if the language has a Wikipedia
    const wikiList = await getWikis();
    if (lang in wikiList) {
        console.log(`Language detected as ${wikiList[lang]} (${lang})`);
        newLang = lang
    } else {
        // Set it to English as default
        console.log("Could not auto-detect language, defaulting to 'en' (English)")
        newLang = 'en'
    }
    // Update language setting
    chrome.storage.local.set({
        userLanguage: newLang
    })
    // Return new language
    return newLang
}